# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "880515e827143201966a57eb1cf5557c"
name = "QR-code"
handle = "qr-code-356"
application_url = "https://shake-against-does-wb.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-0be98dee.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://shake-against-does-wb.trycloudflare.com/auth/callback",
  "https://shake-against-does-wb.trycloudflare.com/auth/shopify/callback",
  "https://shake-against-does-wb.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
